---
- hosts: all
  connection: local
  gather_facts: False

  collections:
    - paloaltonetworks.panos

  tasks: 

  - name: Get the system info
    paloaltonetworks.panos.panos_op:
      provider:
#        ip_address: "{{ ansible_host }}"
        ip_address: 192.168.0.21
#        username: "{{ ansible_username }}"
        username: admin
#        password: "{{ ansible_password }}"
        password: admin
        cmd: 'show system info'
    register: res

  - debug:
      msg: '{{ res.stdout }}'
