---
- hosts: pan-fw1.home
  name: Get facts
  gather_facts: false
  connection: local

  vars:
    provider:
      ip_address: 192.168.0.21
      username: admin
      password: admin

  tasks:

  - name: Show provider info
    debug:
      var: provider

#  - name: Check to see if device is ready
#    paloaltonetworks.panos.panos_op:
#      provider: '{{ provider }}'
#      cmd: 'show chassis-ready'
#    changed_when: false
#    register: result
#    until: result is not failed and (result.stdout | from_json).response.result == 'yes'
#    retries: 50
#    delay: 30

  - name: Get facts
    paloaltonetworks.panos.panos_facts:
      provider: '{{ provider }}'
      gather_subset: ['config']
